import Footer from "@/layouts/Footer/Footer";
import Navbar from "@/layouts/Navbar/Navbar";
import "@/styles/globals.scss";
import "@/styles/reset.scss";
import LenisProvider from "@/utils/LenisProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="rating" content="general" />
        <meta name="rating" content="5" />
        <meta name="revisit" content="3" />
        <meta name="robots" content="index, follow" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap" rel="stylesheet" />
      </head>

      <body>
        <Navbar />

        <LenisProvider>
          {children}
        </LenisProvider>

        <Footer />
      </body>
    </html>
  );
}
